{% set name = "mc" %}
{% set version = "4.8.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.midnight-commander.org/downloads/mc-{{ version }}.tar.xz
  sha256: 773a453112fb6d175a322f042f583af4ad4566d7424fadcfb0f5b61b18c631ca

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - gnuconfig   # [unix]
  host:
    - openssl
    - glib
    - libssh2
    - slang
    - gettext
  run:
    - libssh2
    - slang
    - gettext

test:
  commands:
    - mc --version  # [build_platform == target_platform]

about:
  home: https://www.midnight-commander.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GNU Midnight Commander is a visual file manager
  description: |
    GNU Midnight Commander is a visual file manager, licensed under GNU General
    Public License and therefore qualifies as Free Software. It's a feature
    rich full-screen text mode application that allows you to copy, move and
    delete files and whole directory trees, search for files and run commands
    in the subshell. Internal viewer and editor are included.

    Midnight Commander is based on versatile text interfaces, such as Ncurses
    or S-Lang, which allows it to work on a regular console, inside an X Window
    terminal, over SSH connections and all kinds of remote shells.
  doc_url: https://midnight-commander.org/wiki/doc
  dev_url: https://github.com/MidnightCommander/mc

extra:
  recipe-maintainers:
    - matthiasdiener
